#pragma once

#include "core/Tile.h"

#include <cstddef>
#include <iosfwd>
#include <random>
#include <vector>

class Board {
private:
    std::vector<std::vector<Tile>> grid;
    std::mt19937 randomGenerator;
    int lastMoveScore;

    std::vector<int> processLine(const std::vector<int>& line);
    bool moveLines(bool horizontal, bool reversed);

public:
    static constexpr std::size_t BOARD_SIZE = 4;
    static constexpr int WINNING_VALUE = 2048;

    Board();

    std::size_t getSize() const;
    // Returns a copy. Invalid indices use std::vector::at's bounds checking.
    Tile getTile(std::size_t row, std::size_t col) const;
    void setTile(std::size_t row, std::size_t col, int value);
    void clear();

    bool moveLeft();
    bool moveRight();
    bool moveUp();
    bool moveDown();

    bool addRandomTile();
    // Points generated by the latest move, not the total game score.
    int getLastMoveScore() const;
    bool hasWon() const;
    bool canMove() const;
    bool isGameOver() const;

    bool operator==(const Board& other) const;
    bool operator!=(const Board& other) const;
    friend std::ostream& operator<<(std::ostream& os, const Board& board);
};
